name: bilimusic
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^8.0.1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  dio: ^5.2.1+1
  hooks_riverpod: ^2.3.6
  cached_network_image: ^3.2.3
  desktop_webview_window:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      path: packages/desktop_webview_window
  flutter_inappwebview: ^6.0.0-beta.24+1
  dio_cookie_manager: ^3.1.0
  connectivity_plus: ^4.0.1
  cookie_jar: ^4.0.2
  path_provider: ^2.0.15
  crypto: ^3.0.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_hooks: ^0.18.6
  responsive_grid_list: ^1.3.2
  clipboard: ^0.1.3
  just_audio:
    git:
      url: https://github.com/ryanheise/just_audio.git
      ref: stable  # 使用stable分支
  just_audio_background: ^0.0.1-beta.10
  logger: ^1.4.0
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.6
  audio_video_progress_bar: ^1.0.1
  liquid_swipe: ^3.1.0
  contextmenu: ^3.0.0
  el_tooltip: ^1.0.8
  super_tooltip: ^2.0.4
  flutter_xlider: ^3.5.0
  just_the_tooltip: ^0.0.12
  yaru_window: ^0.1.3
  flutter_svg: ^2.0.7
  chinese_font_library: ^1.0.1
  intl: any
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  memory_cache: ^1.2.0
  path: ^1.8.3
  loadmore: ^2.1.0
  freezed_annotation: ^2.4.1
  easy_refresh: ^3.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.0  # 更新到最新版本
  riverpod_lint: ^1.3.3
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  isar_generator: ^3.1.0+1
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Icon
      fonts:
        - asset: assets/font/icon/iconfont.ttf
