name: Build BiliMusic Windows App

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-artifact
          path: build/windows/x64/runner/Release/**
